# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: ${TZ}
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      #FTLCONF_webserver_api_pwhash: ${WEBSERVER_PWHASH}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: ${DNS_LISTENINGMODE}
      FTLCONF_dns_upstreams: '127.0.0.1#5335' # Unbound
      # Don't use pihole as a NTP/DHCP Server
      FTLCONF_dhcp_active: ${DHCP_ACTIVE}
      FTLCONF_dhcp_ipv6: ${DHCP_IPV6_ACTIVE}
      FTLCONF_ntp_ipv4_active: ${NTP_IPV4_ACTIVE}
      FTLCONF_ntp_ipv6_active: ${NTP_IPV6_ACTIVE}
      FTLCONF_ntp_sync_active: ${NTP_SYNC_ACTIVE}
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - '/srv/docker/pihole-unbound/pihole/etc-pihole:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- '/srv/docker/pihole-unbound/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      #- NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      #- SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
        labels: "service=pihole"
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: alpinelinux/unbound
    # use pihole network stack
    network_mode: service:pihole
    volumes:
      # config files
      - ./unbound-config/unbound.conf:/etc/unbound/unbound.conf:ro
      - ./unbound-config/unbound.conf.d:/etc/unbound/unbound.conf.d:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
        labels: "service=unbound"
    restart: unless-stopped

